### ISSUE TITLE
Hosting My Own / Local Dev Enviornment

### ISSUE THREAD

**Issue by EAWright** [bcgov/common-hosted-form-service#299]
Hi, 

I am looking at demonstrating CHEFs for use by a non-provincial (local/ regional) BC government, however, I have run into a rather tough brick wall.

What I have determined I need for just wetting up a local development instance for demonstration is; an IDIR, plus some non-public files from a confluence page AND a Pathfinder Common Hosted Single Sign-On App from the BCGov. 

While it is possible, through non-trivial effort, for me to remove these dependencies, I am concerned about the future flexibility of use of this Open Source application.

**Comment by EAWright** [comment]
As I'm sure you can appreciate, expanding the number of organizations that use CHEFs has significant benefits to the Province.  The more organizations that use CHEFs, the more likely others will contribute to growing the CHEF feature set

**Comment by jasonchung1871** [comment]
Thanks for posting this here as well as in the RocketChat! Hopefully someone that doesn't have access to the RC can be aware of this topic! I'll quote the answer from our director @matthewhall78 :

> Hi Eric, this is a big and exciting topic that we would love to talk more about. There is an appetite to continue making the CHEFS app more agnostic to a specific Government. I was hoping at some point to connect with a common component team from the Gov of another Province who might like to collaborate on the project to make that happen.

> The goal is that we will have a set of components that can be used together to quickly build out a service that can do all the basic capabilities.
> - Discover
> - Submit
> - Processing

> Getting there one step at a time, as we work on making more and more things loosely coupled so you can choose to use your own choice of components (object storage for example).

> But ya, today your assessment is correct that the products are implemented within a BCGov use case with several dependancies. We have a massive modernization effort ahead of us so focusing internally is necessary, although you are correct in the importance of expanding the number of organizations that use these Components, so we also need to be building for orgs outside of gov to use, and sooner rather than later.

The discussion can be located: https://chat.developer.gov.bc.ca/channel/common-components?msg=JnvRK3Wdk2xDk2afh
