### ISSUE TITLE
Create docker-compose.yml file for non-BCGov users

### ISSUE THREAD

**Issue by jonathan-longe** [bcgov/common-hosted-form-service#415]
Hey, I've created a demo of CHEFS for the Government of Yukon.  Are you interested in incorporating a pull request that adds a sub-directory containing a docker-compose.yml file, scripts and documentation for users outside the BCGov that want to either demo CHEFS or build a local development environment?

As I see it, the following services need to be available for organizations outside BCGov that want to use CHEFS.
- a Postgres database instance;
- a Keycloak instance; and,
- a Common Hosted Email Service (CHES) instance

By making it easier for organizations to use CHEFS, you make it more likely that other organizations will adopt and contribute to CHEFS.  However, I recognize that these changes will add a sub-directory and documentation that may not be of interest to your primary audience -- BCGov users.  

As there's a bit of work to write the documentation and create the pull request, could I get you let me know if you're interested in this PR before I spend time and expense for my client?

Thanks for your consideration!  CHEFS is a great tool.  I so appreciate the time and effort you all have put into this software.

**Comment by AndyBrennan69** [comment]
Hey - thanks for engaging the team.  My senior full stack developer has pointed me this way to reach back out to you.  

There are a sizable number of features and dependencies - within BC Gov components and beyond - to evaluate prior to unleashing forms.io and CHEFS to a wider customer base.  
Your enthusiasm in your project means your team would be a potential partner in these planning efforts.

My product roadmap and vision for sure includes the ability to have a forms design product that is accessible to a wider base than BC Gov.  Capacity and priority wise this isn't for the immediate future. 

Id suggest we keep in contact and see if roadmaps and capabilities align in future quarters.

**Comment by jonathan-longe** [comment]
Thanks @AndyBrennan69 That totally makes sense.  I really appreciate you being candid regarding your team's current priorities and capacities.
