### ISSUE TITLE
Cannot remove "Panel" label from form

### ISSUE THREAD

**Issue by MonicaG** [bcgov/common-hosted-form-service#482]
#### Describe the bug

The label "Panel" is displayed when a Panel is used in a Data Grid. I don't think it should be displayed as it does not provide any information to the user, and is a potential distraction.

#### To Reproduce

1. Go to [Common Hosted Forms](https://submit.digital.gov.bc.ca/app/)
2. Click on [Create A Form](https://submit.digital.gov.bc.ca/app/form/create)
3. Drag a Data Grid onto the screen ( I'm using a Data Grid because I'd like to use the ["Add another" functionality](https://github.com/bcgov/common-hosted-form-service/wiki/Repeating-Data-Grids))
4. Drag a Panel into the Data Grid
5. Give the Panel a name in the settings menu
6. Add any field(s) to the panel
7. Click Save
8. Click Preview
9. The label "Panel" appears above the Panel layout.

#### Expected behavior

I would like the word Panel to not be displayed above the panel. Just the text I entered into the Panel's name field.

#### Screenshots

<img width="1212" alt="Preview_Panel_Text_Displayed" src="https://user-images.githubusercontent.com/2236277/211671802-245fed23-fd18-4db5-b137-bf5d7a5010fe.png">

##### Editor View

<img width="1228" alt="Editor_View" src="https://user-images.githubusercontent.com/2236277/211671920-b4638a70-f772-4939-a384-aba0c31fc704.png">

##### Panel Component's Settings:
<img width="1392" alt="Panel_Settings" src="https://user-images.githubusercontent.com/2236277/211672001-57830cfe-6e85-499b-a8fa-2c98c44bf17e.png">

##### Data Grid Component's Settings:
https://user-images.githubusercontent.com/2236277/211672069-618e431a-3d2b-4de0-a265-a7004c97cc2b.mov

#### Desktop (please complete the following information)

- OS: macOS Ventura (13.1)
- Browser: Safari
- Version: 16.2

**Comment by jasonchung1871** [comment]
Thank you for the very detailed and succinct issue. I'll raise this issue in our daily scrum tomorrow!

**Comment by matthewhall78** [comment]
There is a simple and an advanced field type for "panel".   The simple panel doesn't have the option to hide the label.
