### ISSUE TITLE
Couple minor UI issues (Export Submissions and Select Columns)

### ISSUE THREAD

**Issue by loneil** [bcgov/common-hosted-form-service#513]
#### Describe the bug
Noticed a couple minor UI/UX issues on the Submissions screen when looking at a form I was creating.

1
On the Export Submissions to File popup there are 2 headers for "Select the submission date". Think the first one is a typo.

2
On the Select Columns popup there is a info circle icon on its own with blank area next to it. It doesn't seem to be tied to any action or text on the screen?

See screenshots below

#### To Reproduce

1
- Go to your list of Submissions for a form
- Click the Export Submissions button
- See the popup

2 
- Go to your list of Submissions for a form
- Click the Select Columns button
- See the popup

#### Expected behavior

1
Probably means "Select Data"?

2
Not sure if there's supposed to be text next to this icon, or if it's meant to click or hover.

#### Screenshots
![image](https://user-images.githubusercontent.com/17445138/213828079-9bffc793-8f57-48ca-b0a5-3fab2f1412e1.png)

![image](https://user-images.githubusercontent.com/17445138/213828096-c934e1e2-32f3-4261-8f0a-918b2479f4c2.png)

**Comment by WalterMoar** [comment]
Item 1 was fixed in #668, which did a big rework of the exports.
Item 2 was fixed in #588, which did a big rework of the table columns dialog.
