### ISSUE TITLE
Update the Common Hosted Forms link on the Wiki Page

### ISSUE THREAD

**Issue by MonicaG** [bcgov/common-hosted-form-service#526]
#### Describe the bug

Clicking the "[Common Hosted Form Service (CHEFS)](https://chefs.nrs.gov.bc.ca/app/)" link on the [Wiki](https://github.com/bcgov/common-hosted-form-service/wiki) page results in a server not found error.

#### To Reproduce

1. Click on the Wiki tab in this repo
2. Click on 'Common Hosted Form Service (CHEFS)' link in the first sentence
3. See error

#### Expected behavior

It should link to [https://submit.digital.gov.bc.ca/app/](https://submit.digital.gov.bc.ca/app/)

#### Screenshots

![Page with link](https://user-images.githubusercontent.com/2236277/215824453-c1a54057-1de5-416d-9e39-104620a06205.png)
![Server not found screen](https://user-images.githubusercontent.com/2236277/215824651-94b9c1dd-0b06-4af8-b819-3982ebfe65e3.png)

#### Desktop (please complete the following information)

- OS: [macOS - Ventura 13.1 (22C65)]
- Browser [safari]
- Version [16.2]

**Comment by jasonchung1871** [comment]
Thank you, Monica. Resolved, I'll try to do a quick once over to fix some links! 😄
