### ISSUE TITLE
CSV Export places 

### ISSUE THREAD

**Issue by MonicaG** [bcgov/common-hosted-form-service#536]
#### Describe the bug

Data is not placed in the correct columns when exporting submissions to CSV.  The columns affected are those that were conditionally displayed. 

#### To Reproduce

1. Create a form that contains fields that use conditional logic. 
2. Create form submissions where there are submissions that use the conditional fields and submissions that don't
3. Export the data as CSV
4. Open the CSV file. The conditional field data will be placed in the wrong column

#### Expected behavior

Data should appear in the correct columns

#### Screenshots

If you need example data I can share the exported CSV file.

#### Desktop (please complete the following information)

- OS: MacOS Ventura 13.1
- Browser: Safari
- Version: 16.2

#### Additional context

I was able to get around the problem by exporting the data as json. I then used the [jq command line tool](https://stedolan.github.io/jq/) to convert it to CSV via the following command:

```bash
cat submissions.json | jq -r '(. | map(leaf_paths) | unique) as $cols | map (. as $row | ($cols | map(. as $col | $row | getpath($col)))) as $rows | ([($cols | map(. | map(tostring) | join(".")))] + $rows) | map(@csv) | .[]' > output.csv
```
[Reference](https://stackoverflow.com/a/69230819/4704303)

I wanted to share this work around incase anyone else needs it.

**Comment by WalterMoar** [comment]
Hello @MonicaG - This problem was fixed recently in #892
