### ISSUE TITLE
Time Out when adding team member permissions

### ISSUE THREAD

**Issue by lglossop** [bcgov/common-hosted-form-service#711]
When trying to add members to review forms i get time out issue

My forms/Manage/Team management

1. Go to My Forms
2. Click on Manage/Team Management
3. See error

<img width="767" alt="image" src="https://github.com/bcgov/common-hosted-form-service/assets/128745155/4c9172cf-8298-4176-a7e4-270243851619">

#### Desktop (please complete the following information)

Tried with and without vpn
Cleared Cache/opened in private mode
- Browser edge and chrome

**EMCR has activated preoc's and these forms need to go live on Monday May 15**

**Comment by timisenco2015** [comment]
Thank you for the very detailed issue. We are working on resolving this issue.

**Comment by WalterMoar** [comment]
Hello @lglossop - these problems were resolved in #716 and #718. If you have any further problems, please let us know.
