### ISSUE TITLE
Unviewed submissions - Can we please make them obvious?

### ISSUE THREAD

**Issue by kpmular** [bcgov/common-hosted-form-service#723]
Hello, 

I am working with CHEFS a lot and I am hearing that submission reviewers of forms really, seriously, are wishing  that unviewed submissions (i.e., submissions they have not opened themselves), were obvious. For example, like when you have an unread email, its bold, and when it is opened/viewed, it is automatically unbolded. Similarly there is the ability to mark an email read/unread.

Can a feature like this (especially the first one mentioned) please be added at your earliest convenience? It would make a huge difference and sizeable improvement in user efficiency, experience, and satisfaction. 

Thank you for your time.

**Comment by WalterMoar** [comment]
Hello @kpmular - can you please add this to our feature request system over at https://chefs-fider.apps.silver.devops.gov.bc.ca/ ? That way other people can vote on it and add comments or other suggestions. Thank you!

**Comment by bcgov-citz-ccft** [comment]
Oh, I see that it has already been added - closing this as an issue and we'll use Fider to track it.

https://chefs-fider.apps.silver.devops.gov.bc.ca/posts/66/unviewed-submissions-can-we-please-make-them-obvious

**Comment by kpmular** [comment]
Wonderful, thanks!

Fingers crossed. This is a huge barrier to our work that I am hearing about constantly from users in our department.

All the best,
Kimberly


________________________________
