### ISSUE TITLE
Maximum Character Setting

### ISSUE THREAD

**Issue by lglossop** [bcgov/common-hosted-form-service#741]
Is there a setting to set the maximum characters allowed? I can't find any documentation and our forms have no maximum which is causing issues.

**Comment by WalterMoar** [comment]
Hello! Do you mean maximum characters for Text Field or Multi-Line Text components? If so, then you can set limits in the `Validation` tab of the component:

![image](https://github.com/bcgov/common-hosted-form-service/assets/35532993/2bf8bae3-58a9-46f1-b860-50f3afbbfc4e)

Once this is set, a validation error looks like this:

![image](https://github.com/bcgov/common-hosted-form-service/assets/35532993/1090dd03-b5fd-418a-99cf-d3ff11853aad)

You can do likewise for the Multi-Line Text component.

Note also that in the `Display` tab of the components you can also enable the `Show Character Counter` item if you want it to be shown:

![image](https://github.com/bcgov/common-hosted-form-service/assets/35532993/e3e6f836-cd58-4682-ae52-469bc66c18ea)

**Comment by lglossop** [comment]
That’s perfect, thanks so much.

Lindsey A. Glossop, PMP
Product Manager, OpenShift/MS Dynamics
Ministry of Emergency Management and Climate Readiness

Skype: 778-698-8791 | Cell: 778-677-1549
